src/types/Campaign.ts, src/types/CampaignBudget.ts
While testing the library it came up that some optional fields were missing from `NewCampaignBudgetConfig` and `NewCampaignConfig`
Some of the fields for `NewCampaignConfig` are mutually exclusive (e.g. `manual_cpc` and `target_spend` can't exist in the same call) so I'm not sure how you want to handle that. One potential solution could be to do something like this:
```typescript
type RequireOnlyOne<T, Keys extends keyof T = keyof T> = Pick<
T,
Exclude<keyof T, Keys>
> &
{
[K in Keys]-?: Required<Pick<T, K>> &
Partial<Record<Exclude<Keys, K>, undefined>>
}[Keys];
interface BaseNewCampaignConfig extends NewEntityConfig {
...
}
export type NewCampaignConfig = RequireOnlyOne<BaseNewCampaignConfig, 'manual_cpc', 'manual_cpm'>
```
But there are more entities that have the same situation so I …
=> Update CampaignBudget and Campaign Types

src/Customer.ts, src/Http.ts, src/attributes.ts, src/constants.ts, src/entities/ConversionActions.ts, src/entities/GeoTargetConstants.ts, src/tests/CampaignAdSchedules.test.ts, src/tests/adgroupAds.test.ts, src/tests/adgroupKeywords.test.ts, src/tests/adgroups.test.ts, src/tests/campaignNegatives.test.ts, src/tests/campaignSharedSets.test.ts, src/tests/conversionActions.test.ts, src/tests/customer.test.ts, src/tests/geoTargetConstants.test.ts, src/tests/report.test.ts, src/types/ConversionAction.ts, src/types/Customer.ts, src/types/GeoTargetConstant.ts, src/types/Http.ts, src/utils.ts
This just exposes the update method for the Customer object. That way you can change the customer name, enable auto tagging, enable call reporting, etc.
Edit: Actually if you want to hold off on merging this I'd like to add in the [ConversionActionService](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v0.services#google.ads.googleads.v0.services.ConversionActionService) and everything can be done at once. Unless you'd prefer to keep them separate.
=> add update, conversionActions, and geoTargetConstants methods to Customer

src/utils.ts
When updating some entities, there are Message data types that can be sent using an empty object and a field mask to set them. For instance, on campaigns, setting the bidding strategy to maximize_conversions would look like this:
```javascript
{ update: { maximize_conversions: {} }
```
The API will accept this and change the bidding strategy as long as the field mask is set. This change will just make sure the field mask is set if the update has an empty object in one of the arguments.
=> Allow empty object for Message data types

README.md, package.json, src/customer.ts, src/error.ts, src/services/customer.ts, src/services/service.ts, src/tests/customer.test.ts, src/types.ts
This PR adds support for a new global customer mutate method, that supports creating/updating/deleting multiple resources, of different types, in the same query (as well as using temporary resource ids, as per https://github.com/Opteo/google-ads-api/issues/15).
It is atomic by default, and can be changed to continue on failures using the `partial_failure` option. It also supports the already used `validate_only` option. 
~For now, we just support create operations. At some point, we can make it support updates (either here or a new global mutate method). Support for updates has been added, all it requires is using the `_operation` field. By default `_operation` is `"create"`. In the example below, we create a new campaign budget and update an existing campaign to use it:~ **All operations …
=> Global customer mutate method

src/client.ts, src/customer.ts, src/index.ts, src/services/customer.ts
This PR adds a `Customer` interface type, which can be accessed via the `google-ads-api` import. 
Before, this type was inferred, and didn't work correctly in some TypeScript use-cases. This is purely for TS and doesn't introduce any breaking changes for normal users.
```typescript
import { CustomerInstance } from "google-ads-api"
const customer: CustomerInstance = new client.Customer(...)
```
=> Customer interface type

src/grpc.ts, src/tests/query_limits.test.ts
fix(report): Fixed issue with pagination cutting off results when no `limit` is set.
=> Fix for issue #48

src/tests/utils.test.ts, src/types.ts, src/utils.ts
This PR allows more natural constraints:
```javascript
// before
constraints: {
'campaign.resource_name': `"${rn}"`
}
// after
constraints: {
'campaign.resource_name': rn
}
```
=> feat(report): automatically add quotes around constraint values

src/tests/utils.test.ts, src/utils.ts
At the moment, this constraint doesn't work:
```javascript
customer.report({
entity: 'ad_group',
attributes: ['ad_group.name'],
constraints: {
'campaign.id': [123, 456],
},
})
```
The code always assumes that we want "=", whereas here want "IN" for the operator. This PR corrects this behaviour.
=> fix(report): allow `IN` clause when using object-style constraints

src/services/bidding_strategy.ts
This fixes an error in creating bidding strategies whereby the function to create was not being found (bidding strategies were unable to be created) due to a discrepancy in the case of the `MUTATE_METHOD` name (`mutatebiddingStrategies` vs. `mutateBiddingStrategies`) in bidding_strategy.js.
=> Fix case error in mutateBiddingStrategies constant that causes error

src/services/recommendation.ts, src/tests/recommendation.test.ts
Adds a methods to allow users to apply & dismiss recommendations.
Recommendations can be retrieved but not applied or dismissed.
You can now apply or dismiss recommendations using the resource name.
Since [ApplyRecommendationRequest](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.services#google.ads.googleads.v2.services.ApplyRecommendationRequest) and [DismissRecommendationRequest](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.services#google.ads.googleads.v2.se …
=> Add applyRecommendation & dismissRecommendation to Recommendation Service

.vscode/settings.json, package.json, src/client.ts, src/grpc.ts, src/test_utils.ts, src/tests/customer.test.ts, yarn.lock
This introduces new options to the `Customer` instance, allowing support for [prevent mutations](https://github.com/opteo/google-ads-node#safe-mode) and [logging](https://github.com/opteo/google-ads-node#logging). Two new useful features from our google-ads-node library.
Also, typescript has been upgraded so we can use optional chaining 🎉 
Currently there is no support for these options.
The new fields are `prevent_mutations` and `logging`. Details of these settings can be found in [google-ads-node](https://github.com/opteo/google-ads-node#client-options).
An …
=> Support for prevent mutations & logging from google-ads-node

src/types.ts
The new version of typescript is more strict, which causes some errors when using any kind of bid simulation. 
The fields are 
- `AdGroupCriterionSimulationFields`
- `AdGroupSimulationFields`
- `CampaignCriterionSimulationFields`
These are direct imports from `google-ads-node`.
=> Added 3 fields to types.ts 

src/customer.ts, src/services/customer.ts, src/tests/customer.test.ts
- This allows generics to be used on the report method within the customer instance
- No generics
- Can now **optionally** use generics. No change of current report behaviour if no generics are used (will default to any[])
=> feat(generics): Adding generics to report on customer instance

src/services/conversion_upload.ts, src/services/service.ts, src/tests/conversion_upload.test.ts
**Conversion Upload Service**
- Unfortunately this is quite an annoying service to test as you actually need to attribute clicks and calls to the upload. We tried to fake it, and got as far as if we can get a response from Google we are assuming it will work correctly.
usage
```ts
const call_conversions: CallConversion[] = [
{
caller_id: `+442087599036`,
call_start_date_time: `2020-04-01 12:32:45-08:00`,
conversion_date_time: `2020-04-01 12:32:45-08:00`,
conversion_action: `customers/${CID}/conversionActions/401955561`,
},
]
const res = await customer.conversionUploads.uploadCallConversions(call_conversions)
```
=> feat(conversion_upload): Adding conversion upload service

package.json, src/customer.ts, src/grpc.ts, src/services/customer.ts, src/services/service.ts, src/tests/error.test.ts, src/tests/report.test.ts, src/types.ts, yarn.lock
Feature update to the `report` and `query` method
Currently you can't specify the summary row setting
You can now specifiy `summary_row` in the `report` method, using `enums.SummaryRowSetting`. By default, it's set to `NO_SUMMARY_ROW`.
**Report Example**:
```ts
// Summary row with results (added to the end of the results array)
customer.report({
entity: 'campaign',
metrics: ['metrics.cost_micros', 'metrics.clicks', 'metrics.impressions'],
summary_row: enums.SummaryRowSetting.SUMMARY_ROW_WITH_RESULTS,
})
// Summary row only (only item in the results array) …
```
=> feat(report): added support for specifying summary row setting

src/grpc.ts, yarn.lock
Bug fix
*   **What is the current behavior?**
In reports with the number of rows > page_size and SummaryRowSetting = SUMMARY_ROW_WITH_RESULTS, the summary row is inserted after the first page, but it is only available in the last page.
summaryRow is added after all normal rows
=> Add summaryRow after all normal results

package.json, src/services/service.ts, src/tests/customer.test.ts, yarn.lock
Upgraded google-ads-node to 1.15.5
google-ads-node is at version 1.15.4
Upgraded google-ads-node to 1.15.5, plus a minor fix for partial failure error formatting and some linting.
This should speed up most queries (particularly for large datasets), see the gads node PR for more details: https://github.com/Opteo/google-ads-node/pull/45
=> chore(deps): upgraded google-ads-node to 1.15.5

package.json, yarn.lock
Dependency upgrade
The summary row isn't correctly parsed. See here https://github.com/Opteo/google-ads-node/pull/46
The summary row is correctly parsed. See here https://github.com/Opteo/google-ads-node/pull/46
=> chore(deps): upgraded google-ads-node to 1.15.6

package.json, yarn.lock
Release
google-ads-node is at version 1.15.6
Upgraded google-ads-node to 1.15.7
Fixed a bug around incorrectly removing valid `value` fields. See here: https://github.com/Opteo/google-ads-node/pull/47
=> chore(deps): upgraded google-ads-node to 1.15.7

src/customer.ts
- fixes #147 an issue where we are unable to use the new services from v4.0.0
- No new services! 
- Access to 4 new services from Google Ads Api v4.0.0
=> fix(api): Now exposing the newly added services

package.json, yarn.lock
Fixing an issue where the ThirdPartyAnalyticsAppLinkService was not being found within google-ads-node
This service doesn't exist when asked for
The service now exists
=> fix: applying correct service names within google ads node

src/error.ts, src/grpc.ts, src/services/service.ts, src/tests/policy_violation.test.ts
Upstream support for this fix https://github.com/Opteo/google-ads-node/pull/60. I've also fixed some minor type issues and added tests for policy violations
=> fix(errors): expose policy violation details when received

package.json, src/tests/labels.test.ts, yarn.lock
This PR updates google-ads-node to v2.0.4 so that the `labels.create` method now works correctly. I've also added a test for this method.
Labels cannot be created and fail due to a proto error.
Changes pulled in from google-ads-node v2.0.4
See these issues for context: https://github.com/Opteo/google-ads-node/issues/62, https://github.com/Opteo/google-ads-node/issues/64
Thanks to @akhtariev for reporting this issue!
=> fix: labels.create method + google-ads-node 2.0.4

scripts/services.ts, src/customer.spec.ts, src/customer.ts, src/hooks.ts, src/protos/autogen/serviceFactory.ts, src/service.ts
- Moved hooks to `service.ts` so they can be accessed in `serviceFactory.ts.`
- Minor edits to available mutation hook arguments
- Recompiled services with mutation hooks
=> feat: added mutation hooks to services

README.md, scripts/services.ts, src/customer.spec.ts, src/customer.ts, src/protos/autogen/serviceFactory.ts, src/service.spec.ts, src/service.ts, src/testUtils.ts
- Decode partial failure errors if received in the response (only if enabled in the request)
- Support for `customer.mutateResources` and all valid service mutations e.g. `sharedSets.update`
- Recompiled services
=> Partial failure error decoding

README.md, src/customer.spec.ts, src/customer.ts, src/query.spec.ts, src/query.ts, src/testUtils.ts, src/types.ts
- Summary row field working for `report`. If getting summary row and data, then the summary will be the **first** row of the returned data.
- Summary row field working for `reportStream`. If getting summary row and data then the summary will be the **last** iterated row.
- Result count using a new function `reportCount` that acts like `report` but returns a number representing the number of rows in the query.
=> fix: summary row and result count report options

src/parser.spec.ts, src/parser.ts
In the raw response from Google sometimes fields are simply not present rather than being set to `null`. This fix ensures the parser doesn't crash if this happens, and sets the field to `null` if it doesn't exist.
Thanks to @loicadolphe for discovering this.
=> fix: parser error when field is not present

src/parser.spec.ts, src/parser.ts
As seen in #224 there is a parsing issue for multi line queries. Luckily we already have a function that is designed to normalise a multi-line query to a single line for tests. Therefore this will be a very short fix.
=> fix: fixed parser breaking for multi line queries

README.md, src/query.spec.ts, src/query.ts, src/types.ts
This PR deprecates the `order_by` and `sort_order` report options in favour of a new key `order`. The `order` key takes an array of objects, each having a `field` key for an attribute, metric or segment, and an optional `sort_order` key. If no sort order is provided then the default sort order is `DESC`. The order of the items in the `order` array will match to the order of the order by clauses in the GAQL query.
The `order_by` and `sort_order` report options will still remain available for the time being, with plans to remove them in a future version.
e.g.
```ts
const response = await customer.report({
entity: "campaign",
attributes: ["campaign.id"],
metrics: ["metrics.clicks", "metrics.impressions"],
order: [
{ field: "metrics.clicks", sort_order: "DESC" },
{ field: …
```
=> feat: order report option for multiple order by and sort orders

package.json, yarn.lock
This improves performance of the client constructors by caching the proto imports.
=> deps: upgraded google-ads-node to 4.0.2

src/query.spec.ts, src/query.ts, src/types.ts
This PR allows date constants to be used as a constraint value without wrapping them in quotation marks (which breaks them)
=> fix: date constants are now useable as constraint values

README.md, src/customer.spec.ts, src/customer.ts, src/hooks.ts, src/index.ts, src/protos/autogen/serviceFactory.ts, src/service.ts
As requested in https://github.com/Opteo/google-ads-api/issues/237, this PR brings a new method `reportStreamRaw`. The new function returns the raw stream, allowing the user to handle the `data`, `error` and `end` events manually. As the data events contain un-parsed rows, this PR also exposes the `parse` function. The timeout of data retrieval functions has also been set to 1 hour (Google's recommended) from the default (1 minute) to avoid `4 DEADLINE_EXCEEDED: Deadline exceeded` errors.
There are a few breaking changes in this PR:
- Query hooks no longer apply to the `reportStream` and `reportStreamRaw` methods. These functions now use the stream hooks `onStreamStart` (used in both) and `onStreamError` (used in `reportStream` only). There is no `onStreamEnd` hook as we want to avoid …
=> feat: raw report stream customer method

src/customer.spec.ts, src/customer.ts, src/testUtils.ts
Today, when calling `report()`, we page though the results, then parse all the results at once. This has two drawbacks:
- For hundreds of thousands of rows, this can cause the JS event loop to be locked for longer than reasonable while parsing.
- The parser holds the whole original array in memory at once and builds up the parsed array. Towards the end of this operation, both arrays are kept in memory. This can use more RAM than necessary, and in extreme cases we've seen nodejs processes crash due to OOM errors.
This PR parses each page as it is returned from Google. 
- This means that we never parse more than `10,000` rows at a time, spreading out CPU load. 
- It also ensures that we never hold more than `20,000` rows in memory at a time in the parse() function.
Ideally we'd just use …
=> Parse rows per-page for better performance

package.json, yarn.lock
Includes the following from google-ads-node:
- Upgraded google-gax to 2.22.0
- Recompiled protos to enable new legacy proto load feature
=> deps: upgraded google-ads-node to 6.1.2

src/utils.spec.ts, src/utils.ts
Due to floating point shenanigans, the multiplication in `toMicros()` sometimes _adds_ decimal points. Eg:
This can cause bid mutations to fail with `Bid has too many fractional digit precision.`
In this PR, I round the result to get us back to a whole number, which micros should always be:
I've also added a new test, which fails without this PR.
=> fix: round return value of toMicros

tsconfig.json
Based on https://www.npmjs.com/package/@tsconfig/node12 the target for node12 should be `es2019`.
It reduced the size from 
to
=> Transpile ts to js code that suitable for Node 12

README.md
Hello!
I tinkered a little bit with the library and I found out that the hook examples in README are not following the type definitions, so those examples return a type error.
Currently, the examples include a `hook` property inside the first argument of the `Customer()` method. But such first argument follows the `CustomerOptions` interface, which doesn't have that `hooks` property.
Actually, the method `Customer()` accepts two arguments, the second one being the designated to include the hooks (following the `Hooks` interface).
This PR updates the hook examples in README to make it compliant with the library and the type definitions.
Not an expert on this library, so double-check of what I'm saying is recommended :)
Hope it helps! :raised_hands:
=> Fix hook examples on README

src/query.spec.ts, src/query.ts, src/types.ts
Adds the `parameters` field to the report options, allowing users to specify [parameters](https://developers.google.com/google-ads/api/docs/query/structure#parameters).
=> feat: added parameters to report options

src/customer.ts, src/query.ts
- Fixes an issue where calling `reportStream()` would mutate the `reportOptions` parameter's `limit`, which is an unwanted side effect.
- Sprinkled in a few `Readonly<>` wrappers around key functions to try to prevent this kind of bug in the future.
=> fix: avoid mutating reportOptions when calling reportStream()

src/utils.ts
It is currently not possible to update nullable fields to null because the `recursiveFieldMaskSearch` function fails when it tries to extract `Object.keys` from null. This behaviour is happening because `typeof null === "object"`
Here is a simple fix for that.
=> Fix recursiveFieldMaskSearch

README.md
I've noticed when I copied and tried the error handling example in the readme, it was giving me typescript errored so figured I'd fix it. Thank you ✨ 
TypeScript error I got without the`.query_error`
```
This comparison appears to be unintentional because the types 'IErrorCode' and 'QueryError' have no overlap.
```
After the fix, no Typescript error.
=> adding missing .query_error to err handling readme ex

CHANGELOG.md, package.json, src/query.spec.ts, src/types.ts
- Fix issue with `search_settings` not showing valid fields and its broken type. This was due to the ommission not referencing the correct field with a typo of `SearchGoogleAdsRequest["search_settings"]` rather than `ISearchGoogleAdsRequest["search_settings"]`. I've used the more explicit type `ISearchSettings` just for clarity here.
=> Fix: Type error for ISearchSettings

src/service.ts
When creating multiple Google Ads API client instances with the same refresh token but different OAuth2 credentials, the service cache was causing collisions. This happened because the cache key was only using the service name and refresh token, without considering the client used.
Updated the cache key to include the client ID:
```typescript
const serviceCacheKey = `${service}_${this.clientOptions.client_id}_${this.customerOptions.refresh_token}`;
```
- ✅ Prevents cache collisions between different client instances
- ✅ Ensures each client instance uses its own cached services
- ✅ Maintains proper authentication context per client
- ✅ No breaking changes to existing API
=> Prevent cache collision when using multiple client instances with same refresh token
